import { Header } from '@/components/header/header';
import './globals.css';
import { Roboto } from 'next/font/google';
import { Footer } from '@/components/footer/footer';
import { QueryProvider } from '@/utils/queryProvider';
import { CartProvider } from '@/utils/cartProvider';

const roboto = Roboto({ weight: ['400', '500', '700'], subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <QueryProvider>
          <CartProvider>
            <Header />
            {children}
            <Footer />
          </CartProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
